id = "gleam-theme"
name = "Gleam Theme"
schema_version = 1
version = "0.1.0"
authors = ["Danielle Maywood <danielle@themaywoods.com>"]
description = "Theme inspired by gleam.run"
repository = "https://github.com/DanielleMaywood/gleam-theme-zed"
